<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRxZZvu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRxZZvu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRxZZvu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRxZZvu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXRxZZvu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XRxZZvu',
    'container.build_id' => '53bac5d8',
    'container.build_time' => 1552118139,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRxZZvu');
