<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2o6pYw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2o6pYw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2o6pYw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2o6pYw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX2o6pYw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X2o6pYw',
    'container.build_id' => 'dc4a46af',
    'container.build_time' => 1552101807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2o6pYw');
